<a href="https://colab.research.google.com/github/M1nseokSong/data_science_study/blob/main/numpy_study.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

array1 = np.array([1,2,3,4,5,6,7,8,9])
print(array1>4)
print(array1[array1>4])
print(np.where(array1>4))
print(array1[np.where(array1>4)])
print(array1.max())
print(array1.mean())
print(np.median(array1))
print(array1.std())
print(array1.var())



[False False False False  True  True  True  True  True]
[5 6 7 8 9]
(array([4, 5, 6, 7, 8]),)
[5 6 7 8 9]
9
5.0
5.0
2.581988897471611
6.666666666666667


In [4]:
array2 = np.full(6,7)
array3 = np.zeros(6, dtype=int)
array4 = np.ones(6, dtype=int)
array5 = np.random.random(6)
array6 = np.arange(6)
array7 = np.arange(2, 7)
array8 = np.arange(3, 17, 3)

array1, array2, array3, array4, array5, array6, array7, array8

(array([1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([7, 7, 7, 7, 7, 7]),
 array([0, 0, 0, 0, 0, 0]),
 array([1, 1, 1, 1, 1, 1]),
 array([0.1742508 , 0.73307754, 0.52750538, 0.41349924, 0.01441168,
        0.45973835]),
 array([0, 1, 2, 3, 4, 5]),
 array([2, 3, 4, 5, 6]),
 array([ 3,  6,  9, 12, 15]))